# Site settings
title: Maya Preeya Jewelry
email: mayapreeya@icloud.com
description: You can have your description in this box; for now I'll put in simple filler text like what you are reading right now. This is filler text meant to occupy some space. Please change
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maya-preeya.github.io" # the base hostname & protocol for your site
twitter_username: baesedandy
github_username:  andykamath

# Build settings
markdown: kramdown
